### PR TITLE
Build building hours pages

### PR DESCRIPTION
**Pull request by weonthank**

### CODE REVIEW

**Comment by weonthank** [comment]
Wow! That was fast!

**Comment by ninamariepeterson** [comment]
Something broke.


            Property 'saturdayClosed' does not exist on type 'BuildingDetailsPage'. Did you mean 'saturdayClose'?



      L21:  if (this.building.saturday.close == 'closed') {

      L22:    this.saturdayClosed = true;

**Comment by ninamariepeterson** [comment]
Casey fixed the typo Will.

**Comment by ninamariepeterson** [comment]
There are two arrows on the iOS Building Hours page.  Please add something that detects if it an iOS or android and only adds an arrow to the android. Thanks.

**Pull request merged**
